name: sports_event_app
description: "A dynamic Flutter app for managing and displaying sports events."

# Prevents publishing to any package repositories
publish_to: 'none'

# Versioning aligned with semantic versioning standards
version: 1.0.0+1

# Dart SDK constraints ensuring compatibility and future-proofing
environment:
  sdk: '>=3.2.3 <4.0.0'

# List of dependencies with explicit versioning for better maintenance
dependencies:
  bloc_test: ^9.1.5
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1
  mocktail: ^1.0.2
  get_it: ^7.6.4
  very_good_analysis: ^5.1.0
  text_scroll: ^0.2.0

# Development-specific dependencies for testing and code generation
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Asset directories for scalable and vector graphics, as well as data files
  assets:
    - assets/fonts/
    - assets/svg/
    - assets/data/

  # Custom font configuration for enhanced UI aesthetics
  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
